# Generated by Django 5.2.5 on 2025-08-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('DEVELOPMENT', 'Development'), ('DESIGN', 'Design'), ('SECURITY', 'Security'), ('TESTING', 'Testing'), ('INFRASTRUCTURE', 'Infrastructure'), ('RESEARCH', 'Research'), ('MARKETING', 'Marketing'), ('ANALYTICS', 'Analytics'), ('DEVOPS', 'Devops'), ('AI/ML', 'AI/ML')], default='DEVELOPMENT', max_length=100),
        ),
    ]
